services:
  db:
    image: postgres:"postgres:15"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=delivery
  delivery:
    image: payara/server-full:6.2023.3-jdk17
    ports:
      - 8080:8080
      - 4848:4848
    working_dir: /DELIVERY
    volumes:
      - ./:/DELIVERY
      - ./postgresql-42.5.3.jar:/opt/payara/appserver/glassfish/domains/domain1/lib/postgresql-42.5.3.jar
      - ./init.sh:/opt/init.sh:ro
    depends_on:
      - db
    command: ["bash","-c","/opt/init.sh"]